server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/unnoba

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: catalog-event-service
          uri: lb://catalog-event-service
          predicates:
            - Path=/admin/artists/**,/artists/**,/artists,/admin/events/**,/events/**,/events

        - id: user-social-service
          uri: lb://user-social-service
          predicates:
            - Path=/admin/users/**,/admin/users,/auth/register,/me/following/**,/me/following,/me/favorite-events/**,/me/favorite-events

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/me/notifications/**,/me/notifications
