server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/unnoba

cloud:
  gateway:
    default-filters:
      - TokenRelay
    routes:
      - id: catalog-event-service
        uri: lb://CATALOG-EVENT-SERVICE
        predicates:
          - Path=/admin/users/**, /admin/artists/**, /artists/**, /admin/events/**, /events/**

      - id: user-social-service
        uri: lb://USER-SOCIAL-SERVICE
        predicates:
          - Path=/auth/register, /me/following/**, /me/favorite-events**

      - id: notification-service
        uri: lb://NOTIFICATION-SERVICE
        predicates:
          - Path=/me/notifications/**
