server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-social-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_social_db
    username: root
    password: insecure
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/unnoba

keycloak-admin:
  server-url: http://localhost:8080
  realm: unnoba
  client-id: pdyc
  client-secret: Kfs6fbShlz87GUNy9nldFrbINC4Bfems
