spring.application.name=greater-events
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/pdyc2026
spring.datasource.username=root
spring.datasource.password=insecure
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/unnoba
keycloak.client-secret=Kfs6fbShlz87GUNy9nldFrbINC4Bfems
